### ISSUE TITLE
Small issue: raw process cinit defaults to mean, but params say interp

### ISSUE THREAD

**Issue by petertorelli** [jetperch/pyjoulescope#18]
The cinit() function defaults to MEAN suppression, but the parameter help says 'interp' is default.

**Comment by mliberty1** [comment]
I see that the defaults for raw_processor.pxi does not match the defaults specified in parameters_v1.py.  While the do not need to match (parameters_v1.py will win), the conflict can lead to confusion.  Will fix.  Thanks!

**Comment by mliberty1** [comment]
Fixed in 0.9.3.
